alloy:
  securityContext:
    privileged: true
    runAsGroup: 0
    runAsUser: 0
    capabilities:
      add:
        - PERFMON
        - SYS_PTRACE
        - SYS_RESOURCE
        - SYS_ADMIN
        - SYS_BPF
        - NET_ADMIN

  configMap:
    create: true
    content: |
      logging {
        level = "debug"
        format = "logfmt"
      }
      
      discovery.kubernetes "local_pods" {
        selectors {
          field = "spec.nodeName=" + env("HOSTNAME")
          role = "pod"
        }
        selectors {
          field = "status.phase=Running"
          label = "app in (java-fast-slow, python-fast-slow, cpu-stress)"
          role = "pod"
        }
        role = "pod"
      }
      
      pyroscope.ebpf "instance" {
        forward_to = [pyroscope.write.endpoint.receiver]
        targets = discovery.kubernetes.local_pods.targets
      }
      
      pyroscope.write "endpoint" {
        endpoint {
          url = "http://pyroscope.pyroscope:4040"
        }
      }
  controller:
    hostPID: true
    privileged: true
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
