apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # needed for the discovery.kubernetes alloy component
metadata:
  name: grafana-alloy-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch

