apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-alloy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-alloy-role
subjects:
  - kind: ServiceAccount
    name: grafana-alloy
    namespace: pyroscope-ebpf

